### ISSUE TITLE
overseerr - Download Failed

### ISSUE THREAD

**Issue by kerniger** [brettpetch/hosted-scripts#10]
when using
bash <(curl -sL "https://github.com/brettpetch/hosted-scripts/raw/master/overseerr.sh")

I get "Download Failed" after "Downloading and extracting source code"

**Comment by WowSuchRicky** [comment]
I got this too, you might have to `su` as the user you installed Swizzin with. If you're logged in as root, it will be trying to install stuf into /home/root which may not exist or you may not have permissions for.

**Comment by brettpetch** [comment]
> I got this too, you might have to `su` as the user you installed Swizzin with. If you're logged in as root, it will be trying to install stuff into /home/root which may not exist or you may not have permissions for. 
> 
> 
> 
> Basically, it's the symptom of issue #1 

This is not meant to be run as root. Nor is it meant for dedicated systems.
