### ISSUE TITLE
[BUG] overseerr - `python` is not a valid npm option

### ISSUE THREAD

**Issue by WowSuchRicky** [brettpetch/hosted-scripts#12]
### What happened?

Steps to reproduce:

1. Run curl command in README to install overseer
2. Receive error during 'Installing dependencies via yarn':  `npm ERR! `python` is not a valid npm option` 

Expected results:
Installation should succeed.

Suspiciously related: https://stackoverflow.com/a/74523071/2402061
https://github.com/brettpetch/hosted-scripts/blob/master/overseerr.sh#L50 npm doesn't seem to like setting arbitrary config values as of some recent version, which is likely breaking this. 

I also do have python installed and `which python` doesn't seem to error out when I run it manually so I am a bit confused why that if statement is triggering; may be mis config on my part though. 

### Relevant logs and output

```plaintext
nvm is already installed.
Node LTS installed.
Installing Yarn
Yarn installed.
Downloading and extracting source code
Code extracted
Installing dependencies via yarn
npm ERR! `python` is not a valid npm option

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/r/.npm/_logs/2023-04-04T21_13_25_987Z-debug-0.log
```

**Comment by willadamskeane** [comment]
Running into the same issue.

**Comment by eliob83** [comment]
A workaround is to downgrade npm to version 8:
`npm install -g npm@^8`
