### ISSUE TITLE
[BUG]  29.ein.itsby.design the lounge problem

### ISSUE THREAD

**Issue by rogales** [brettpetch/hosted-scripts#18]
### What happened?

Hello, after yesterdays server maintance I cant enable/install or even uninstall the lounge by ssh.
I cant even uninstall this app, because I gives me an error: https://i.imgur.com/biYikKY.png
When I try to run enable/stop/start/status/restart it gives me the same error which is:

https://i.imgur.com/Qvsnewn.png

Expected results: To make it work as earlier.

**Comment by brettpetch** [comment]
This seems to be an issue with your user account not sourcing the appropriate environment variables.
