### ISSUE TITLE
"enable authentication prior to setting it up"

### ISSUE THREAD

**Issue by angelod1as** [brettpetch/hosted-scripts#2]
In the [Mylar3 script](https://github.com/brettpetch/hosted-scripts/blob/master/mylar3.sh) there's a line, at the end of the installation: 

```
Mylar is now installed. Please be sure to enable authentication prior to setting it up
```

What do you mean by that? I ran the script, accessed the URL outputted in my console and it did not work. By this text, I don't know exactly what I should've done.

I'm running it in a HostingByDesign SSH

**Comment by brettpetch** [comment]
Just something that needs to be removed. Auth was a last minute addition to the script.

**Comment by angelod1as** [comment]
Oh so I can ignore this warning, is that what you mean? Thanks!

**Comment by brettpetch** [comment]
Yep. That’s why I closed the issue and edited the script ;b. The warning can be ignored. Sent from my iPhoBNOn Sep 26, 2022, at 12:08 AM, Angelo Dias ***@***.***> wrote:﻿
Oh so I can ignore this warning, is that what you mean? Thanks!
