### ISSUE TITLE
[BUG] GuestFTP -  hostingby.design

### ISSUE THREAD

**Issue by XinfitX** [brettpetch/hosted-scripts#22]
### What happened?

guestftp no works with secure FXP transfer.
https://www.wftpserver.com/kb_secureftp.htm

error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter

Possible fix for FXP SSL Transfer ?

Thanks very much.

**Comment by brettpetch** [comment]
SSLv3 has been depreciated for quite a while. See POODLE. https://www.cisa.gov/news-events/alerts/2014/10/17/ssl-30-protocol-vulnerability-and-poodle-attackOn Mar 26, 2024, at 7:02 AM, XinfitX ***@***.***> wrote:﻿
What happened?
What happened?
guestftp no works with secure FXP transfer.
https://www.wftpserver.com/kb_secureftp.htm
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
Possible fix for FXP SSL Transfer ?
Thanks very much.
Relevant logs and output
No response
